config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/admin', to: 'admins#dashboard'

  resources :admin_merchants, except: [:destroy]

  # get '/admin/merchants', to: 'admin_merchants#index'
  # patch '/admin/merchants/:id', to: 'admin_merchants#update'
  # get '/admin/merchants/new', to: 'admin_merchants#new'
  # get '/admin/merchants/:id', to: 'admin_merchants#show'
  # get '/admin/merchants/:id/edit', to: 'admin_merchants#edit'
  # post '/admin/merchants', to: 'admin_merchants#create'

  get '/admin/invoices', to: 'admin_invoices#index'
  get '/admin/invoices/:id', to: 'admin_invoices#show'
  patch '/admin/invoices/:id', to: 'admin_invoices#update'

  get '/merchants/:id/dashboard', to: 'merchants#dashboard'
  get '/merchants/:id/invoices', to: 'merchant_invoices#index'
  get '/merchants/:id/invoices/:invoice_id', to: 'merchant_invoices#show'
  patch '/merchants/:id/invoices/:invoice_id', to: 'merchant_invoices#update'

  get '/merchants/:id/items', to: 'merchant_items#index'
  get '/merchants/:id/items/new', to: 'merchant_items#new'
  post '/merchants/:id/items', to: 'merchant_items#create'
  get '/merchants/:id/items/:item_id', to: 'merchant_items#show'
  get '/merchants/:id/items/:item_id/edit', to: 'merchant_items#edit'
  patch '/merchants/:id/items/:item_id', to: 'merchant_items#update'

end

app/controllers/admin_merchants_controller.rb
class AdminMerchantsController < ApplicationController
  def index
    @merchants = Merchant.all
  end

  def show
    @merchant = Merchant.find(params[:id])
  end

  def edit
    @merchant = Merchant.find(params[:id])
  end

  def update
    if params[:merchant_id]
      merch = Merchant.find(params[:merchant_id])
      if merch.status == "disabled"
        merch.status = "enabled"
      else
        merch.status = "disabled"
      end
      merch.save
      redirect_to admin_merchants_path
    else
      merch = Merchant.find(merch_params[:id])
      merch.update(merch_params)
      redirect_to admin_merchant_path(merch)
      flash[:message] = 'Merchant has been successfully updated!'
    end
  end

  def new

  end

  def create
    merchant = Merchant.create!(merch_params)
    redirect_to admin_merchants_path
  end

  private

  def merch_params
    params.permit(:id, :name)
  end
end

app/views/admin_merchants/_form.html.erb
<%= form_with url: path, method: method, local: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit button_text %>
<% end %>

app/views/admin_merchants/edit.html.erb
<h1>Edit <%= @merchant.name %></h1>
<%= render partial: "form", locals: { path: admin_merchant_path(@merchant), method: :patch, button_text: "Save" } %>

app/views/admin_merchants/index.html.erb
<h1>Admin Merchant Index Page</h1>
<%= link_to "Create a New Merchant", new_admin_merchant_path %>
<div id="top-5-merchants">
<h2>Top 5 Merchants by Total Revenue Generated:</h2>
  <% @merchants.top_five_merchants_by_revenue.each do |merchant| %>
      <%= link_to "#{merchant.name}", admin_merchant_path(merchant) %>
      <p>Generated <%= merchant.total_revenue %> revenue</p>
      <p>Top selling date for us was: <%= merchant.merchant_best_day.strftime('%B %e, %Y') %></p>
  <% end %>
</div>


<div id="enabled-merchants">
  <h2>Enabled Merchants:</h2>
  <% @merchants.enabled_merchants.each do |merchant| %>
   <div id="merchant-<%= merchant.id %>">
    <p>Name: <%= merchant.name %></p>
    <p>Status: <%= merchant.status %></p>
    <p><%= button_to "Disable", admin_merchant_path(merchant, :merchant_id => "#{merchant.id}"), method: :patch, local: true %></p>
    </div><hr>
   <% end %>
</div>
<div id="disabled-merchants">
  <h2>Disabled Merchants:</h2>
  <% @merchants.disabled_merchants.each do |merchant| %>
  <div id="merchant-<%= merchant.id %>">
    <p>Name: <%= merchant.name %></p>
    <p>Status: <%= merchant.status %></p>
    <p><%= button_to "Enable", admin_merchant_path(merchant, :merchant_id => "#{merchant.id}"), method: :patch, local: true %></p>
    </div><hr>
    <% end %>
</div>

app/views/admin_merchants/new.html.erb
<h1>New Merchant</h1>
<hr>

<%= render partial: "form", locals: { path: admin_merchants_path,  method: :post, button_text: "Submit" } %>

app/views/admin_merchants/show.html.erb
<h2>Merchant Name: <%= @merchant.name %></h2><br>

<%= link_to 'Update Merchant', edit_admin_merchant_path(@merchant) %>